from __future__ import annotations
import os
_SONNET = "claude-sonnet-4-6"
_HAIKU = "claude-haiku-4-5-20251001"

ORCHESTRATOR_MODEL = os.getenv("ORCHESTRATOR_MODEL", _SONNET)
RECOMMENDATION_MODEL = os.getenv("RECOMMENDATION_MODEL", _SONNET)
CODEBASE_MODEL = os.getenv("CODEBASE_MODEL", _SONNET)
FRONTEND_SENTRY_MODEL = os.getenv("FRONTEND_SENTRY_MODEL", _HAIKU)
BACKEND_SENTRY_MODEL = os.getenv("BACKEND_SENTRY_MODEL", _HAIKU)
RENDER_LOGS_MODEL = os.getenv("RENDER_LOGS_MODEL", _HAIKU)
GITHUB_MODEL = os.getenv("GITHUB_MODEL", _HAIKU)

